spring.application.name=auth-service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/colegio_db?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:0000}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Habilitar integración con Azure AD
spring.cloud.azure.active-directory.enabled=true
# Client ID del registro del API en Entra ID
spring.cloud.azure.active-directory.credential.client-id=0b636eb1-e3df-4939-8a32-ef3e24411dad
# Application ID URI configurado en "Expose an API"
spring.cloud.azure.active-directory.app-id-uri=api://0b636eb1-e3df-4939-8a32-ef3e24411dad
