spring.application.name=bff-colegio
server.port=${SERVER_PORT:8080}

services.notas.url=${NOTAS_SERVICE_URL:http://localhost:8082/api/notas}
services.asistencia.url=${ASISTENCIA_SERVICE_URL:http://localhost:8083/api/asistencias}
services.auth.url=${AUTH_SERVICE_URL:http://localhost:8081/api}
